export const ACRONYMS = [

  { acronym: "ACL", expansion: ["Access", "Control", "List"], difficulty: "easy" },
  { acronym: "ADSL", expansion: ["Asymmetric", "Digital", "Subscriber", "Line"], difficulty: "easy" },
  { acronym: "AES67", expansion: ["Audio", "Engineering", "Society", "67"], difficulty: "medium" },
  { acronym: "AF", expansion: ["Assured", "Forwarding"], difficulty: "easy" },
  { acronym: "AH", expansion: ["Authentication", "Header"], difficulty: "medium" },
  { acronym: "AP", expansion: ["Access", "Point"], difficulty: "easy" },
  { acronym: "API", expansion: ["Application", "Programming", "Interface"], difficulty: "easy" },
  { acronym: "ARP", expansion: ["Address", "Resolution", "Protocol"], difficulty: "easy" },
  { acronym: "AS", expansion: ["Autonomous", "System"], difficulty: "medium" },
  { acronym: "ASN", expansion: ["Autonomous", "System", "Number"], difficulty: "medium" },
  { acronym: "ATM", expansion: ["Asynchronous", "Transfer", "Mode"], difficulty: "medium" },
  { acronym: "BGP", expansion: ["Border", "Gateway", "Protocol"], difficulty: "medium" },
  { acronym: "BSS", expansion: ["Basic", "Service", "Set"], difficulty: "easy" },
  { acronym: "BYOD", expansion: ["Bring", "Your", "Own", "Device"], difficulty: "easy" },
  { acronym: "CAPWAP", expansion: ["Control", "And", "Provisioning", "Of", "Wireless", "Access", "Points"], difficulty: "hard" },
  { acronym: "CDN", expansion: ["Content", "Delivery", "Network"], difficulty: "medium" },
  { acronym: "CIDR", expansion: ["Classless", "Inter", "Domain", "Routing"], difficulty: "medium" },
  { acronym: "CIFS", expansion: ["Common", "Internet", "File", "System"], difficulty: "medium" },
  { acronym: "CSMA", expansion: ["Carrier", "Sense", "Multiple", "Access"], difficulty: "medium" },
  { acronym: "CSMA/CD", expansion: ["Carrier", "Sense", "Multiple", "Access", "Collision", "Detection"], difficulty: "medium" },
  { acronym: "CSMA/CA", expansion: ["Carrier", "Sense", "Multiple", "Access", "Collision", "Avoidance"], difficulty: "medium" },
  { acronym: "CWDM", expansion: ["Coarse", "Wavelength", "Division", "Multiplexing"], difficulty: "hard" },
  { acronym: "DAC", expansion: ["Direct", "Attach", "Copper"], difficulty: "easy" },
  { acronym: "DDNS", expansion: ["Dynamic", "DNS"], difficulty: "easy" },
  { acronym: "DHCP", expansion: ["Dynamic", "Host", "Configuration", "Protocol"], difficulty: "easy" },
  { acronym: "DIFS", expansion: ["DCF", "Interframe", "Space"], difficulty: "hard" },
  { acronym: "DMZ", expansion: ["Demilitarized", "Zone"], difficulty: "medium" },
  { acronym: "DNS", expansion: ["Domain", "Name", "System"], difficulty: "easy" },
  { acronym: "DNSSEC", expansion: ["DNS", "Security", "Extensions"], difficulty: "hard" },
  { acronym: "DOCSIS", expansion: ["Data", "Over", "Cable", "Service", "Interface", "Specification"], difficulty: "hard" },
  { acronym: "DSCP", expansion: ["Differentiated", "Services", "Code", "Point"], difficulty: "medium" },
  { acronym: "DSL", expansion: ["Digital", "Subscriber", "Line"], difficulty: "easy" },
  { acronym: "DSSS", expansion: ["Direct", "Sequence", "Spread", "Spectrum"], difficulty: "hard" },
  { acronym: "EAPOL", expansion: ["EAP", "Over", "LAN"], difficulty: "medium" },
  { acronym: "EIGRP", expansion: ["Enhanced", "Interior", "Gateway", "Routing", "Protocol"], difficulty: "hard" },
  { acronym: "ESP", expansion: ["Encapsulating", "Security", "Payload"], difficulty: "medium" },
  { acronym: "FDDI", expansion: ["Fiber", "Distributed", "Data", "Interface"], difficulty: "hard" },
  { acronym: "FQDN", expansion: ["Fully", "Qualified", "Domain", "Name"], difficulty: "easy" },
  { acronym: "FTP", expansion: ["File", "Transfer", "Protocol"], difficulty: "easy" },
  { acronym: "FTPS", expansion: ["FTP", "Secure"], difficulty: "easy" },
  { acronym: "GRE", expansion: ["Generic", "Routing", "Encapsulation"], difficulty: "medium" },
  { acronym: "HFC", expansion: ["Hybrid", "Fiber", "Coax"], difficulty: "medium" },
  { acronym: "HMAC", expansion: ["Hash", "Message", "Authentication", "Code"], difficulty: "medium" },
  { acronym: "HTTP", expansion: ["Hypertext", "Transfer", "Protocol"], difficulty: "easy" },
  { acronym: "HTTPS", expansion: ["Hypertext", "Transfer", "Protocol", "Secure"], difficulty: "easy" },
  { acronym: "ICMP", expansion: ["Internet", "Control", "Message", "Protocol"], difficulty: "easy" },
  { acronym: "ICS", expansion: ["Industrial", "Control", "System"], difficulty: "medium" },
  { acronym: "IDS", expansion: ["Intrusion", "Detection", "System"], difficulty: "medium" },
  { acronym: "IGMP", expansion: ["Internet", "Group", "Management", "Protocol"], difficulty: "medium" },
  { acronym: "IKE", expansion: ["Internet", "Key", "Exchange"], difficulty: "medium" },
  { acronym: "IMAP", expansion: ["Internet", "Message", "Access", "Protocol"], difficulty: "easy" },
  { acronym: "IoT", expansion: ["Internet", "of", "Things"], difficulty: "easy" },
  { acronym: "IPAM", expansion: ["IP", "Address", "Management"], difficulty: "medium" },
  { acronym: "IPSec", expansion: ["Internet", "Protocol", "Security"], difficulty: "medium" },
  { acronym: "IPv4", expansion: ["Internet", "Protocol", "Version", "4"], difficulty: "easy" },
  { acronym: "IPv6", expansion: ["Internet", "Protocol", "Version", "6"], difficulty: "medium" },
  { acronym: "ISDN", expansion: ["Integrated", "Services", "Digital", "Network"], difficulty: "medium" },
  { acronym: "ISP", expansion: ["Internet", "Service", "Provider"], difficulty: "easy" },
  { acronym: "LACP", expansion: ["Link", "Aggregation", "Control", "Protocol"], difficulty: "medium" },
  { acronym: "LAN", expansion: ["Local", "Area", "Network"], difficulty: "easy" },
  { acronym: "LLDP", expansion: ["Link", "Layer", "Discovery", "Protocol"], difficulty: "medium" }
  { acronym: "LTE", expansion: ["Long", "Term", "Evolution"], difficulty: "easy" },
  { acronym: "MAC", expansion: ["Media", "Access", "Control"], difficulty: "easy" },
  { acronym: "MAN", expansion: ["Metropolitan", "Area", "Network"], difficulty: "easy" },
  { acronym: "MIMO", expansion: ["Multiple", "Input", "Multiple", "Output"], difficulty: "medium" },
  { acronym: "MPLS", expansion: ["Multi", "Protocol", "Label", "Switching"], difficulty: "hard" },
  { acronym: "MTU", expansion: ["Maximum", "Transmission", "Unit"], difficulty: "easy" },
  { acronym: "NAT", expansion: ["Network", "Address", "Translation"], difficulty: "easy" },
  { acronym: "NDP", expansion: ["Neighbor", "Discovery", "Protocol"], difficulty: "medium" },
  { acronym: "NGFW", expansion: ["Next", "Generation", "Firewall"], difficulty: "medium" },
  { acronym: "WAF", expansion: ["Web", "Application", "Firewall"], difficulty: "medium" },
  { acronym: "NIC", expansion: ["Network", "Interface", "Card"], difficulty: "easy" },
  { acronym: "NTP", expansion: ["Network", "Time", "Protocol"], difficulty: "easy" },
  { acronym: "OCSP", expansion: ["Online", "Certificate", "Status", "Protocol"], difficulty: "medium" },
  { acronym: "OFDM", expansion: ["Orthogonal", "Frequency", "Division", "Multiplexing"], difficulty: "hard" },
  { acronym: "OSPF", expansion: ["Open", "Shortest", "Path", "First"], difficulty: "medium" },
  { acronym: "OTG", expansion: ["On", "The", "Go"], difficulty: "easy" },
  { acronym: "PAP", expansion: ["Password", "Authentication", "Protocol"], difficulty: "easy" },
  { acronym: "PAT", expansion: ["Port", "Address", "Translation"], difficulty: "easy" },
  { acronym: "PoE", expansion: ["Power", "over", "Ethernet"], difficulty: "easy" },
  { acronym: "POP3", expansion: ["Post", "Office", "Protocol", "3"], difficulty: "easy" },
  { acronym: "PPP", expansion: ["Point", "to", "Point", "Protocol"], difficulty: "easy" },
  { acronym: "PPPoE", expansion: ["PPP", "over", "Ethernet"], difficulty: "easy" },
  { acronym: "QoS", expansion: ["Quality", "of", "Service"], difficulty: "medium" },
  { acronym: "RADIUS", expansion: ["Remote", "Authentication", "Dial", "In", "User", "Service"], difficulty: "medium" },
  { acronym: "RDP", expansion: ["Remote", "Desktop", "Protocol"], difficulty: "easy" },
  { acronym: "RIP", expansion: ["Routing", "Information", "Protocol"], difficulty: "easy" },
  { acronym: "RSTP", expansion: ["Rapid", "Spanning", "Tree", "Protocol"], difficulty: "medium" },
  { acronym: "SCP", expansion: ["Secure", "Copy", "Protocol"], difficulty: "medium" },
  { acronym: "SDN", expansion: ["Software", "Defined", "Networking"], difficulty: "medium" },
  { acronym: "SFTP", expansion: ["Secure", "File", "Transfer", "Protocol"], difficulty: "easy" },
  { acronym: "SIP", expansion: ["Session", "Initiation", "Protocol"], difficulty: "medium" },
  { acronym: "SLAAC", expansion: ["Stateless", "Address", "Autoconfiguration"], difficulty: "medium" },
  { acronym: "SMB", expansion: ["Server", "Message", "Block"], difficulty: "easy" },
  { acronym: "SMTP", expansion: ["Simple", "Mail", "Transfer", "Protocol"], difficulty: "easy" },
  { acronym: "SNMP", expansion: ["Simple", "Network", "Management", "Protocol"], difficulty: "medium" },
  { acronym: "SOHO", expansion: ["Small", "Office", "Home", "Office"], difficulty: "easy" },
  { acronym: "SSH", expansion: ["Secure", "Shell"], difficulty: "easy" },
  { acronym: "SSID", expansion: ["Service", "Set", "Identifier"], difficulty: "easy" },
  { acronym: "SSL", expansion: ["Secure", "Sockets", "Layer"], difficulty: "medium" },
  { acronym: "STP", expansion: ["Spanning", "Tree", "Protocol"], difficulty: "medium" },
  { acronym: "TACACS", expansion: ["Terminal", "Access", "Controller", "Access", "Control", "System"], difficulty: "hard" },
  { acronym: "TCP", expansion: ["Transmission", "Control", "Protocol"], difficulty: "easy" },
  { acronym: "TFTP", expansion: ["Trivial", "File", "Transfer", "Protocol"], difficulty: "easy" },
  { acronym: "TLS", expansion: ["Transport", "Layer", "Security"], difficulty: "medium" },
  { acronym: "UDP", expansion: ["User", "Datagram", "Protocol"], difficulty: "easy" },
  { acronym: "UPnP", expansion: ["Universal", "Plug", "and", "Play"], difficulty: "easy" },
  { acronym: "URL", expansion: ["Uniform", "Resource", "Locator"], difficulty: "easy" },
  { acronym: "UTP", expansion: ["Unshielded", "Twisted", "Pair"], difficulty: "easy" },
  { acronym: "VLAN", expansion: ["Virtual", "Local", "Area", "Network"], difficulty: "easy" },
  { acronym: "VoIP", expansion: ["Voice", "over", "IP"], difficulty: "easy" },
  { acronym: "VPN", expansion: ["Virtual", "Private", "Network"], difficulty: "easy" },
  { acronym: "WAN", expansion: ["Wide", "Area", "Network"], difficulty: "easy" },
  { acronym: "WLAN", expansion: ["Wireless", "Local", "Area", "Network"], difficulty: "easy" },
  { acronym: "WPA3", expansion: ["Wi", "Fi", "Protected", "Access", "3"], difficulty: "medium" },

/* -------------------------
   PACK 2 — THREATS & ATTACKS
   ------------------------- */

  { acronym: "APT", expansion: ["Advanced", "Persistent", "Threat"], difficulty: "medium" },
  { acronym: "BEC", expansion: ["Business", "Email", "Compromise"], difficulty: "medium" },
  { acronym: "BOTNET", expansion: ["Botnet"], difficulty: "medium" },
  { acronym: "C2", expansion: ["Command", "and", "Control"], difficulty: "medium" },
  { acronym: "CSRF", expansion: ["Cross", "Site", "Request", "Forgery"], difficulty: "medium" },
  { acronym: "DDoS", expansion: ["Distributed", "Denial", "of", "Service"], difficulty: "medium" },
  { acronym: "DNSPOISON", expansion: ["DNS", "Cache", "Poisoning"], difficulty: "medium" },
  { acronym: "DOS", expansion: ["Denial", "of", "Service"], difficulty: "easy" },
  { acronym: "DRDoS", expansion: ["Distributed", "Reflection", "Denial", "of", "Service"], difficulty: "hard" },
  { acronym: "EAVESDROP", expansion: ["Eavesdropping"], difficulty: "easy" },
  { acronym: "EVILTWIN", expansion: ["Evil", "Twin"], difficulty: "medium" },
  { acronym: "FREAK", expansion: ["Factoring", "RSA", "Export", "Keys"], difficulty: "hard" },
  { acronym: "HOAX", expansion: ["Security", "Hoax"], difficulty: "easy" },
  { acronym: "INSIDER", expansion: ["Insider", "Threat"], difficulty: "medium" },
  { acronym: "JAMMING", expansion: ["Wireless", "Jamming"], difficulty: "medium" },
  { acronym: "KEYLOGGER", expansion: ["Key", "Logger"], difficulty: "easy" },
  { acronym: "MACFLOOD", expansion: ["MAC", "Flooding"], difficulty: "medium" },
  { acronym: "MITM", expansion: ["Man", "in", "the", "Middle"], difficulty: "medium" },
  { acronym: "PHISH", expansion: ["Phishing"], difficulty: "easy" },
  { acronym: "RANSOMWARE", expansion: ["Ransomware"], difficulty: "medium" },
  { acronym: "REPLAY", expansion: ["Replay", "Attack"], difficulty: "medium" },
  { acronym: "ROOTKIT", expansion: ["Rootkit"], difficulty: "medium" },
  { acronym: "SCANNING", expansion: ["Network", "Scanning"], difficulty: "easy" },
  { acronym: "SHOULDER", expansion: ["Shoulder", "Surfing"], difficulty: "easy" },
  { acronym: "SKIMMING", expansion: ["Card", "Skimming"], difficulty: "easy" },
  { acronym: "SMISHING", expansion: ["SMS", "Phishing"], difficulty: "easy" },
  { acronym: "SPOOFING", expansion: ["Identity", "Spoofing"], difficulty: "medium" },
  { acronym: "SPYWARE", expansion: ["Spyware"], difficulty: "easy" },
  { acronym: "SQLI", expansion: ["SQL", "Injection"], difficulty: "medium" },
  { acronym: "TAILGATING", expansion: ["Tailgating"], difficulty: "easy" },
  { acronym: "TROJAN", expansion: ["Trojan", "Horse"], difficulty: "easy" },
  { acronym: "VISHING", expansion: ["Voice", "Phishing"], difficulty: "easy" },
  { acronym: "WATERINGHOLE", expansion: ["Watering", "Hole", "Attack"], difficulty: "medium" },
  { acronym: "WHALING", expansion: ["Whaling"], difficulty: "medium" },
  { acronym: "XSS", expansion: ["Cross", "Site", "Scripting"], difficulty: "medium" },
  { acronym: "ZEROCLICK", expansion: ["Zero", "Click", "Exploit"], difficulty: "hard" },
  { acronym: "ZERODAY", expansion: ["Zero", "Day", "Vulnerability"], difficulty: "hard" },

/* -------------------------
   PACK 3 — IDENTITY & ACCESS
   ------------------------- */

  { acronym: "AAA", expansion: ["Authentication", "Authorization", "Accounting"], difficulty: "easy" },
  { acronym: "ABAC", expansion: ["Attribute", "Based", "Access", "Control"], difficulty: "medium" },
  { acronym: "ACL", expansion: ["Access", "Control", "List"], difficulty: "easy" },
  { acronym: "AD", expansion: ["Active", "Directory"], difficulty: "easy" },
  { acronym: "AES", expansion: ["Advanced", "Encryption", "Standard"], difficulty: "medium" },
  { acronym: "ASLR", expansion: ["Address", "Space", "Layout", "Randomization"], difficulty: "hard" },
  { acronym: "BIOMETRICS", expansion: ["Biometric", "Authentication"], difficulty: "medium" },
  { acronym: "CAC", expansion: ["Common", "Access", "Card"], difficulty: "easy" },
  { acronym: "CAPTCHA", expansion: ["Completely", "Automated", "Public", "Turing", "Test", "To", "Tell", "Computers", "And", "Humans", "Apart"], difficulty: "medium" },
  { acronym: "CASB", expansion: ["Cloud", "Access", "Security", "Broker"], difficulty: "medium" },
  { acronym: "CHAP", expansion: ["Challenge", "Handshake", "Authentication", "Protocol"], difficulty: "medium" },
  { acronym: "DAC", expansion: ["Discretionary", "Access", "Control"], difficulty: "easy" },
  { acronym: "FIDO", expansion: ["Fast", "Identity", "Online"], difficulty: "medium" },
  { acronym: "HOTP", expansion: ["HMAC", "One", "Time", "Password"], difficulty: "medium" },
  { acronym: "IAM", expansion: ["Identity", "And", "Access", "Management"], difficulty: "easy" },
  { acronym: "KERBEROS", expansion: ["Kerberos", "Authentication"], difficulty: "hard" },
  { acronym: "LDAP", expansion: ["Lightweight", "Directory", "Access", "Protocol"], difficulty: "medium" },
  { acronym: "MAC", expansion: ["Mandatory", "Access", "Control"], difficulty: "medium" },
  { acronym: "MFA", expansion: ["Multi", "Factor", "Authentication"], difficulty: "easy" },
  { acronym: "OAUTH", expansion: ["Open", "Authorization"], difficulty: "medium" },
  { acronym: "OIDC", expansion: ["OpenID", "Connect"], difficulty: "medium" },
  { acronym: "PAM", expansion: ["Privileged", "Access", "Management"], difficulty: "medium" },
  { acronym: "PIV", expansion: ["Personal", "Identity", "Verification"], difficulty: "easy" },
  { acronym: "RBAC", expansion: ["Role", "Based", "Access", "Control"], difficulty: "easy" },
  { acronym: "SAML", expansion: ["Security", "Assertion", "Markup", "Language"], difficulty: "medium" },
  { acronym: "SMARTCARD", expansion: ["Smart", "Card"], difficulty: "easy" },
  { acronym: "SSO", expansion: ["Single", "Sign", "On"], difficulty: "easy" },
  { acronym: "TOTP", expansion: ["Time", "Based", "One", "Time", "Password"], difficulty: "easy" },
  { acronym: "U2F", expansion: ["Universal", "2nd", "Factor"], difficulty: "medium" },
  { acronym: "YUBIKEY", expansion: ["YubiKey", "Hardware", "Token"], difficulty: "easy" },
/* -------------------------
   PACK 4 — CRYPTOGRAPHY
   ------------------------- */

  { acronym: "AES", expansion: ["Advanced", "Encryption", "Standard"], difficulty: "medium" },
  { acronym: "AES256", expansion: ["Advanced", "Encryption", "Standard", "256-bit"], difficulty: "medium" },
  { acronym: "BCRYPT", expansion: ["Blowfish", "Crypt"], difficulty: "medium" },
  { acronym: "CBC", expansion: ["Cipher", "Block", "Chaining"], difficulty: "medium" },
  { acronym: "CCMP", expansion: ["Counter", "Mode", "CBC", "MAC", "Protocol"], difficulty: "hard" },
  { acronym: "CHACHA20", expansion: ["ChaCha20", "Stream", "Cipher"], difficulty: "hard" },
  { acronym: "CRL", expansion: ["Certificate", "Revocation", "List"], difficulty: "medium" },
  { acronym: "CSR", expansion: ["Certificate", "Signing", "Request"], difficulty: "medium" },
  { acronym: "DES", expansion: ["Data", "Encryption", "Standard"], difficulty: "easy" },
  { acronym: "DH", expansion: ["Diffie", "Hellman"], difficulty: "medium" },
  { acronym: "DSA", expansion: ["Digital", "Signature", "Algorithm"], difficulty: "medium" },
  { acronym: "ECC", expansion: ["Elliptic", "Curve", "Cryptography"], difficulty: "medium" },
  { acronym: "ECDHE", expansion: ["Elliptic", "Curve", "Diffie", "Hellman", "Ephemeral"], difficulty: "hard" },
  { acronym: "ECDSA", expansion: ["Elliptic", "Curve", "Digital", "Signature", "Algorithm"], difficulty: "hard" },
  { acronym: "FDE", expansion: ["Full", "Disk", "Encryption"], difficulty: "easy" },
  { acronym: "HMAC", expansion: ["Hash", "Message", "Authentication", "Code"], difficulty: "medium" },
  { acronym: "IV", expansion: ["Initialization", "Vector"], difficulty: "easy" },
  { acronym: "KDF", expansion: ["Key", "Derivation", "Function"], difficulty: "medium" },
  { acronym: "MD5", expansion: ["Message", "Digest", "5"], difficulty: "easy" },
  { acronym: "OCSP", expansion: ["Online", "Certificate", "Status", "Protocol"], difficulty: "medium" },
  { acronym: "PBKDF2", expansion: ["Password", "Based", "Key", "Derivation", "Function", "2"], difficulty: "hard" },
  { acronym: "PKI", expansion: ["Public", "Key", "Infrastructure"], difficulty: "medium" },
  { acronym: "PKE", expansion: ["Public", "Key", "Encryption"], difficulty: "medium" },
  { acronym: "RSA", expansion: ["Rivest", "Shamir", "Adleman"], difficulty: "medium" },
  { acronym: "SHA", expansion: ["Secure", "Hash", "Algorithm"], difficulty: "easy" },
  { acronym: "SHA256", expansion: ["Secure", "Hash", "Algorithm", "256-bit"], difficulty: "medium" },
  { acronym: "SHA3", expansion: ["Secure", "Hash", "Algorithm", "3"], difficulty: "medium" },
  { acronym: "TLS", expansion: ["Transport", "Layer", "Security"], difficulty: "medium" },
  { acronym: "X509", expansion: ["X", "509", "Certificate", "Standard"], difficulty: "medium" },
/* -------------------------
   PACK 5 — NETWORK SECURITY TOOLS
   ------------------------- */

  { acronym: "AV", expansion: ["Antivirus"], difficulty: "easy" },
  { acronym: "EDR", expansion: ["Endpoint", "Detection", "And", "Response"], difficulty: "medium" },
  { acronym: "XDR", expansion: ["Extended", "Detection", "And", "Response"], difficulty: "medium" },
  { acronym: "IDS", expansion: ["Intrusion", "Detection", "System"], difficulty: "medium" },
  { acronym: "IPS", expansion: ["Intrusion", "Prevention", "System"], difficulty: "medium" },
  { acronym: "SIEM", expansion: ["Security", "Information", "And", "Event", "Management"], difficulty: "medium" },
  { acronym: "SOAR", expansion: ["Security", "Orchestration", "Automation", "And", "Response"], difficulty: "hard" },
  { acronym: "UEBA", expansion: ["User", "And", "Entity", "Behavior", "Analytics"], difficulty: "medium" },
  { acronym: "NGFW", expansion: ["Next", "Generation", "Firewall"], difficulty: "medium" },
  { acronym: "WAF", expansion: ["Web", "Application", "Firewall"], difficulty: "medium" },
  { acronym: "CASB", expansion: ["Cloud", "Access", "Security", "Broker"], difficulty: "medium" },
  { acronym: "DLP", expansion: ["Data", "Loss", "Prevention"], difficulty: "medium" },
  { acronym: "FIM", expansion: ["File", "Integrity", "Monitoring"], difficulty: "medium" },
  { acronym: "HIDS", expansion: ["Host", "Intrusion", "Detection", "System"], difficulty: "medium" },
  { acronym: "HIPS", expansion: ["Host", "Intrusion", "Prevention", "System"], difficulty: "medium" },
  { acronym: "NAC", expansion: ["Network", "Access", "Control"], difficulty: "medium" },
  { acronym: "NIDS", expansion: ["Network", "Intrusion", "Detection", "System"], difficulty: "medium" },
  { acronym: "NIPS", expansion: ["Network", "Intrusion", "Prevention", "System"], difficulty: "medium" },
  { acronym: "OSINT", expansion: ["Open", "Source", "Intelligence"], difficulty: "easy" },
  { acronym: "PKI", expansion: ["Public", "Key", "Infrastructure"], difficulty: "medium" },
  { acronym: "SIEMMOC", expansion: ["Security", "Information", "Event", "Management", "Monitoring", "Operations", "Center"], difficulty: "hard" },
  { acronym: "SOC", expansion: ["Security", "Operations", "Center"], difficulty: "easy" },
  { acronym: "SOHO", expansion: ["Small", "Office", "Home", "Office"], difficulty: "easy" },
  { acronym: "UEFI", expansion: ["Unified", "Extensible", "Firmware", "Interface"], difficulty: "medium" },
  { acronym: "VMS", expansion: ["Vulnerability", "Management", "System"], difficulty: "medium" },
  { acronym: "VPC", expansion: ["Virtual", "Private", "Cloud"], difficulty: "easy" },
  { acronym: "WIDS", expansion: ["Wireless", "Intrusion", "Detection", "System"], difficulty: "medium" },
  { acronym: "WIPS", expansion: ["Wireless", "Intrusion", "Prevention", "System"], difficulty: "medium" },
/* -------------------------
   PACK 6 — RISK MANAGEMENT & GOVERNANCE
   ------------------------- */

  { acronym: "AUP", expansion: ["Acceptable", "Use", "Policy"], difficulty: "easy" },
  { acronym: "BCP", expansion: ["Business", "Continuity", "Plan"], difficulty: "medium" },
  { acronym: "BIA", expansion: ["Business", "Impact", "Analysis"], difficulty: "medium" },
  { acronym: "COOP", expansion: ["Continuity", "Of", "Operations", "Plan"], difficulty: "medium" },
  { acronym: "CSF", expansion: ["Cybersecurity", "Framework"], difficulty: "medium" },
  { acronym: "CVE", expansion: ["Common", "Vulnerabilities", "And", "Exposures"], difficulty: "easy" },
  { acronym: "CVSS", expansion: ["Common", "Vulnerability", "Scoring", "System"], difficulty: "medium" },
  { acronym: "DRP", expansion: ["Disaster", "Recovery", "Plan"], difficulty: "medium" },
  { acronym: "ERM", expansion: ["Enterprise", "Risk", "Management"], difficulty: "medium" },
  { acronym: "FISMA", expansion: ["Federal", "Information", "Security", "Management", "Act"], difficulty: "hard" },
  { acronym: "GRC", expansion: ["Governance", "Risk", "Compliance"], difficulty: "medium" },
  { acronym: "HIPAA", expansion: ["Health", "Insurance", "Portability", "And", "Accountability", "Act"], difficulty: "hard" },
  { acronym: "IRP", expansion: ["Incident", "Response", "Plan"], difficulty: "medium" },
  { acronym: "ISA", expansion: ["Interconnection", "Security", "Agreement"], difficulty: "medium" },
  { acronym: "ISO27001", expansion: ["ISO", "27001", "Security", "Standard"], difficulty: "hard" },
  { acronym: "MOU", expansion: ["Memorandum", "Of", "Understanding"], difficulty: "easy" },
  { acronym: "MTBF", expansion: ["Mean", "Time", "Between", "Failures"], difficulty: "medium" },
  { acronym: "MTTR", expansion: ["Mean", "Time", "To", "Repair"], difficulty: "medium" },
  { acronym: "NDA", expansion: ["Non", "Disclosure", "Agreement"], difficulty: "easy" },
  { acronym: "NIST", expansion: ["National", "Institute", "Of", "Standards", "And", "Technology"], difficulty: "medium" },
  { acronym: "PII", expansion: ["Personally", "Identifiable", "Information"], difficulty: "easy" },
  { acronym: "POAM", expansion: ["Plan", "Of", "Action", "And", "Milestones"], difficulty: "hard" },
  { acronym: "RA", expansion: ["Risk", "Assessment"], difficulty: "easy" },
  { acronym: "RPO", expansion: ["Recovery", "Point", "Objective"], difficulty: "medium" },
  { acronym: "RTO", expansion: ["Recovery", "Time", "Objective"], difficulty: "medium" },
  { acronym: "SLA", expansion: ["Service", "Level", "Agreement"], difficulty: "easy" },
  { acronym: "SOX", expansion: ["Sarbanes", "Oxley", "Act"], difficulty: "hard" },
  { acronym: "SSA", expansion: ["System", "Security", "Assessment"], difficulty: "medium" },
  { acronym: "SSP", expansion: ["System", "Security", "Plan"], difficulty: "medium" },
  { acronym: "TTP", expansion: ["Tactics", "Techniques", "And", "Procedures"], difficulty: "medium" },
  { acronym: "ALE", expansion: ["Annual", "Loss", "Expectancy"], difficulty: "medium" },
  { acronym: "ARO", expansion: ["Annualized", "Rate", "Of", "Occurrence"], difficulty: "medium" },
  { acronym: "SLE", expansion: ["Single", "Loss", "Expectancy"], difficulty: "medium" },
  { acronym: "EF", expansion: ["Exposure", "Factor"], difficulty: "medium" },
  { acronym: "FRR", expansion: ["False", "Rejection", "Rate"], difficulty: "medium" },
  { acronym: "FAR", expansion: ["False", "Acceptance", "Rate"], difficulty: "medium" },
  { acronym: "CER", expansion: ["Crossover", "Error", "Rate"], difficulty: "medium" },
  { acronym: "RMF", expansion: ["Risk", "Management", "Framework"], difficulty: "hard" },
  { acronym: "CSIRT", expansion: ["Computer", "Security", "Incident", "Response", "Team"], difficulty: "medium" },
  { acronym: "CIRT", expansion: ["Cyber", "Incident", "Response", "Team"], difficulty: "medium" },
  { acronym: "ISSO", expansion: ["Information", "System", "Security", "Officer"], difficulty: "medium" },
  { acronym: "ISO", expansion: ["International", "Organization", "For", "Standardization"], difficulty: "medium" },
  { acronym: "ISAC", expansion: ["Information", "Sharing", "And", "Analysis", "Center"], difficulty: "medium" },
  { acronym: "ISAO", expansion: ["Information", "Sharing", "And", "Analysis", "Organization"], difficulty: "medium" },
  { acronym: "FIPS", expansion: ["Federal", "Information", "Processing", "Standards"], difficulty: "hard" },
  { acronym: "GDPR", expansion: ["General", "Data", "Protection", "Regulation"], difficulty: "hard" },
  { acronym: "PCI-DSS", expansion: ["Payment", "Card", "Industry", "Data", "Security", "Standard"], difficulty: "hard" },
  { acronym: "SCF", expansion: ["Secure", "Control", "Framework"], difficulty: "hard" },
  { acronym: "COBIT", expansion: ["Control", "Objectives", "For", "Information", "And", "Related", "Technologies"], difficulty: "hard" },
  { acronym: "ITIL", expansion: ["Information", "Technology", "Infrastructure", "Library"], difficulty: "hard" },
  { acronym: "SOAR", expansion: ["Security", "Orchestration", "Automation", "And", "Response"], difficulty: "hard" },
  { acronym: "IR", expansion: ["Incident", "Response"], difficulty: "easy" },
  { acronym: "BPA", expansion: ["Business", "Partnership", "Agreement"], difficulty: "easy" },
  { acronym: "ISA", expansion: ["Interconnection", "Security", "Agreement"], difficulty: "medium" },
  { acronym: "MSSP", expansion: ["Managed", "Security", "Service", "Provider"], difficulty: "medium" },
  { acronym: "MSP", expansion: ["Managed", "Service", "Provider"], difficulty: "easy" },
  { acronym: "RM", expansion: ["Risk", "Management"], difficulty: "easy" },
  { acronym: "SAF", expansion: ["Security", "Assessment", "Framework"], difficulty: "hard" },
  { acronym: "TAM", expansion: ["Technical", "Account", "Manager"], difficulty: "easy" },

/* -------------------------
   PACK 7 — CLOUD & VIRTUALIZATION
   ------------------------- */

  { acronym: "API", expansion: ["Application", "Programming", "Interface"], difficulty: "easy" },
  { acronym: "BYOD", expansion: ["Bring", "Your", "Own", "Device"], difficulty: "easy" },
  { acronym: "CASB", expansion: ["Cloud", "Access", "Security", "Broker"], difficulty: "medium" },
  { acronym: "CDN", expansion: ["Content", "Delivery", "Network"], difficulty: "medium" },
  { acronym: "CI", expansion: ["Continuous", "Integration"], difficulty: "medium" },
  { acronym: "CICD", expansion: ["Continuous", "Integration", "Continuous", "Deployment"], difficulty: "medium" },
  { acronym: "CLOUD", expansion: ["Cloud", "Computing"], difficulty: "easy" },
  { acronym: "COOP", expansion: ["Continuity", "Of", "Operations", "Plan"], difficulty: "medium" },
  { acronym: "DaaS", expansion: ["Desktop", "As", "A", "Service"], difficulty: "medium" },
  { acronym: "FaaS", expansion: ["Function", "As", "A", "Service"], difficulty: "medium" },
  { acronym: "HCI", expansion: ["Hyperconverged", "Infrastructure"], difficulty: "medium" },
  { acronym: "IaaS", expansion: ["Infrastructure", "As", "A", "Service"], difficulty: "easy" },
  { acronym: "IDaaS", expansion: ["Identity", "As", "A", "Service"], difficulty: "medium" },
  { acronym: "MDM", expansion: ["Mobile", "Device", "Management"], difficulty: "medium" },
  { acronym: "MFA", expansion: ["Multi", "Factor", "Authentication"], difficulty: "easy" },
  { acronym: "PaaS", expansion: ["Platform", "As", "A", "Service"], difficulty: "easy" },
  { acronym: "SaaS", expansion: ["Software", "As", "A", "Service"], difficulty: "easy" },
  { acronym: "SCIM", expansion: ["System", "For", "Cross", "Domain", "Identity", "Management"], difficulty: "hard" },
  { acronym: "SDN", expansion: ["Software", "Defined", "Networking"], difficulty: "medium" },
  { acronym: "SDS", expansion: ["Software", "Defined", "Storage"], difficulty: "medium" },
  { acronym: "VDI", expansion: ["Virtual", "Desktop", "Infrastructure"], difficulty: "medium" },
  { acronym: "VM", expansion: ["Virtual", "Machine"], difficulty: "easy" },
  { acronym: "VMM", expansion: ["Virtual", "Machine", "Monitor"], difficulty: "medium" },
  { acronym: "VPC", expansion: ["Virtual", "Private", "Cloud"], difficulty: "easy" },
  { acronym: "VPN", expansion: ["Virtual", "Private", "Network"], difficulty: "easy" },
  { acronym: "VTL", expansion: ["Virtual", "Tape", "Library"], difficulty: "medium" },

