export const ACRONYMS = [

  { acronym: "ACL", expansion: ["Access", "Control", "List"], difficulty: "easy" },
  { acronym: "ADSL", expansion: ["Asymmetric", "Digital", "Subscriber", "Line"], difficulty: "easy" },
  { acronym: "AES67", expansion: ["Audio", "Engineering", "Society", "67"], difficulty: "medium" },
  { acronym: "AF", expansion: ["Assured", "Forwarding"], difficulty: "easy" },
  { acronym: "AH", expansion: ["Authentication", "Header"], difficulty: "medium" },
  { acronym: "AP", expansion: ["Access", "Point"], difficulty: "easy" },
  { acronym: "API", expansion: ["Application", "Programming", "Interface"], difficulty: "easy" },
  { acronym: "ARP", expansion: ["Address", "Resolution", "Protocol"], difficulty: "easy" },
  { acronym: "AS", expansion: ["Autonomous", "System"], difficulty: "medium" },
  { acronym: "ASN", expansion: ["Autonomous", "System", "Number"], difficulty: "medium" },
  { acronym: "ATM", expansion: ["Asynchronous", "Transfer", "Mode"], difficulty: "medium" },
  { acronym: "BGP", expansion: ["Border", "Gateway", "Protocol"], difficulty: "medium" },
  { acronym: "BSS", expansion: ["Basic", "Service", "Set"], difficulty: "easy" },
  { acronym: "BYOD", expansion: ["Bring", "Your", "Own", "Device"], difficulty: "easy" },
  { acronym: "CAPWAP", expansion: ["Control", "And", "Provisioning", "Of", "Wireless", "Access", "Points"], difficulty: "hard" },
  { acronym: "CDN", expansion: ["Content", "Delivery", "Network"], difficulty: "medium" },
  { acronym: "CIDR", expansion: ["Classless", "Inter", "Domain", "Routing"], difficulty: "medium" },
  { acronym: "CIFS", expansion: ["Common", "Internet", "File", "System"], difficulty: "medium" },
  { acronym: "CSMA", expansion: ["Carrier", "Sense", "Multiple", "Access"], difficulty: "medium" },
  { acronym: "CSMA/CD", expansion: ["Carrier", "Sense", "Multiple", "Access", "Collision", "Detection"], difficulty: "medium" },
  { acronym: "CSMA/CA", expansion: ["Carrier", "Sense", "Multiple", "Access", "Collision", "Avoidance"], difficulty: "medium" },
  { acronym: "CWDM", expansion: ["Coarse", "Wavelength", "Division", "Multiplexing"], difficulty: "hard" },
  { acronym: "DAC", expansion: ["Direct", "Attach", "Copper"], difficulty: "easy" },
  { acronym: "DDNS", expansion: ["Dynamic", "DNS"], difficulty: "easy" },
  { acronym: "DHCP", expansion: ["Dynamic", "Host", "Configuration", "Protocol"], difficulty: "easy" },
  { acronym: "DIFS", expansion: ["DCF", "Interframe", "Space"], difficulty: "hard" },
  { acronym: "DMZ", expansion: ["Demilitarized", "Zone"], difficulty: "medium" },
  { acronym: "DNS", expansion: ["Domain", "Name", "System"], difficulty: "easy" },
  { acronym: "DNSSEC", expansion: ["DNS", "Security", "Extensions"], difficulty: "hard" },
  { acronym: "DOCSIS", expansion: ["Data", "Over", "Cable", "Service", "Interface", "Specification"], difficulty: "hard" },
  { acronym: "DSCP", expansion: ["Differentiated", "Services", "Code", "Point"], difficulty: "medium" },
  { acronym: "DSL", expansion: ["Digital", "Subscriber", "Line"], difficulty: "easy" },
  { acronym: "DSSS", expansion: ["Direct", "Sequence", "Spread", "Spectrum"], difficulty: "hard" },
  { acronym: "EAPOL", expansion: ["EAP", "Over", "LAN"], difficulty: "medium" },
  { acronym: "EIGRP", expansion: ["Enhanced", "Interior", "Gateway", "Routing", "Protocol"], difficulty: "hard" },
  { acronym: "ESP", expansion: ["Encapsulating", "Security", "Payload"], difficulty: "medium" },
  { acronym: "FDDI", expansion: ["Fiber", "Distributed", "Data", "Interface"], difficulty: "hard" },
  { acronym: "FQDN", expansion: ["Fully", "Qualified", "Domain", "Name"], difficulty: "easy" },
  { acronym: "FTP", expansion: ["File", "Transfer", "Protocol"], difficulty: "easy" },
  { acronym: "FTPS", expansion: ["FTP", "Secure"], difficulty: "easy" },
  { acronym: "GRE", expansion: ["Generic", "Routing", "Encapsulation"], difficulty: "medium" },
  { acronym: "HFC", expansion: ["Hybrid", "Fiber", "Coax"], difficulty: "medium" },
  { acronym: "HMAC", expansion: ["Hash", "Message", "Authentication", "Code"], difficulty: "medium" },
  { acronym: "HTTP", expansion: ["Hypertext", "Transfer", "Protocol"], difficulty: "easy" },
  { acronym: "HTTPS", expansion: ["Hypertext", "Transfer", "Protocol", "Secure"], difficulty: "easy" },
  { acronym: "ICMP", expansion: ["Internet", "Control", "Message", "Protocol"], difficulty: "easy" },
  { acronym: "ICS", expansion: ["Industrial", "Control", "System"], difficulty: "medium" },
  { acronym: "IDS", expansion: ["Intrusion", "Detection", "System"], difficulty: "medium" },
  { acronym: "IGMP", expansion: ["Internet", "Group", "Management", "Protocol"], difficulty: "medium" },
  { acronym: "IKE", expansion: ["Internet", "Key", "Exchange"], difficulty: "medium" },
  { acronym: "IMAP", expansion: ["Internet", "Message", "Access", "Protocol"], difficulty: "easy" },
  { acronym: "IoT", expansion: ["Internet", "of", "Things"], difficulty: "easy" },
  { acronym: "IPAM", expansion: ["IP", "Address", "Management"], difficulty: "medium" },
  { acronym: "IPSec", expansion: ["Internet", "Protocol", "Security"], difficulty: "medium" },
  { acronym: "IPv4", expansion: ["Internet", "Protocol", "Version", "4"], difficulty: "easy" },
  { acronym: "IPv6", expansion: ["Internet", "Protocol", "Version", "6"], difficulty: "medium" },
  { acronym: "ISDN", expansion: ["Integrated", "Services", "Digital", "Network"], difficulty: "medium" },
  { acronym: "ISP", expansion: ["Internet", "Service", "Provider"], difficulty: "easy" },
  { acronym: "LACP", expansion: ["Link", "Aggregation", "Control", "Protocol"], difficulty: "medium" },
  { acronym: "LAN", expansion: ["Local", "Area", "Network"], difficulty: "easy" },
  { acronym: "LLDP", expansion: ["Link", "Layer", "Discovery", "Protocol"], difficulty: "medium" }
  { acronym: "LTE", expansion: ["Long", "Term", "Evolution"], difficulty: "easy" },
  { acronym: "MAC", expansion: ["Media", "Access", "Control"], difficulty: "easy" },
  { acronym: "MAN", expansion: ["Metropolitan", "Area", "Network"], difficulty: "easy" },
  { acronym: "MIMO", expansion: ["Multiple", "Input", "Multiple", "Output"], difficulty: "medium" },
  { acronym: "MPLS", expansion: ["Multi", "Protocol", "Label", "Switching"], difficulty: "hard" },
  { acronym: "MTU", expansion: ["Maximum", "Transmission", "Unit"], difficulty: "easy" },
  { acronym: "NAT", expansion: ["Network", "Address", "Translation"], difficulty: "easy" },
  { acronym: "NDP", expansion: ["Neighbor", "Discovery", "Protocol"], difficulty: "medium" },
  { acronym: "NGFW", expansion: ["Next", "Generation", "Firewall"], difficulty: "medium" },
  { acronym: "WAF", expansion: ["Web", "Application", "Firewall"], difficulty: "medium" },

